chartdetails:
  locales: ["globalv1"]
  main_artists : ["Ariana Grande", "KAROL G", "Taylor Swift", "Beyonc", "Selena Gomez", "SZA", "Nicki Minaj", "Shakira", "Camila Cabello", "Becky G", "Doja Cat", "Lady Gaga", "Megan Thee Stallion"]
